# __데이터 타입__
<br>

### Table of contents
1. [matrix, array](#r2section1)
2. [list](#r2section2)
3. [Data Frame](#r2section3)
4. [Model](#r2section4)
    
<br>

데이터는 여러 형태로 정의될 수 있습니다.  
R에서 데이터를 다루는 대표적인 타입은 matrix, array, dataframe 등이 있습니다.  
* 프로그래밍 언어에 따라 같은 이름의 데이터 타입이라도 성질은 다를 수 있습니다.

<br>

## __matrix, array__ <a name="r2section1"></a>
matrix 는 2차원 행렬 모양의 데이터입니다.

In [1]:
m1 <- matrix(data=c(1,2,3,4,5,6), nrow=3, ncol=2) # 1 ~ 6 6개의 원소를 3*2 형태로  변환하여 matrix 에 넣습니다.  
# 변환 방향은 각 column을 구성하는 순서로 생성됩니다. 
print(m1)

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6


array는 2차원 이상의 데이터를 다룰 수 있습니다.  
데이터의 구성은 dim 을 통해 설정해 줍니다.  
3차원의 경우 2차원 행렬이 여러 개 있는 것으로 생각할 수 있습니다.

In [2]:
a1 <- array(1:24, dim=c(4,3,2)) # row, column, (row, column) : 2*3*(두 개 행렬)
print(a1)

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

, , 2

     [,1] [,2] [,3]
[1,]   13   17   21
[2,]   14   18   22
[3,]   15   19   23
[4,]   16   20   24



In [3]:
# 첫번째 index 는 row, 두 번째 index 는 column, 셋 째 index 는 행렬 입니다.
print(a1[1,1,1])
cat('\n')
print(a1[1,,1])
cat('\n')
print(a1[1,1,]) # 각 행렬로부터의 (1,1) 값과 모든 셋 째 index
cat('\n')
print(a1[2,1,1:2]) # 1:2 는 1, 2
cat('\n')
print(a1[,,1]) # 셋 째 행렬의 모든 row, column
cat('\n')
print(a1[,c(1,3),2]) # 2번째 행렬의 1,3번째 컬럼 값
dim(a1) <- c(2,3,4) # dimension 변환

[1] 1

[1] 1 5 9

[1]  1 13

[1]  2 14

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7   11
[4,]    4    8   12

     [,1] [,2]
[1,]   13   21
[2,]   14   22
[3,]   15   23
[4,]   16   24


<br>

## __list__ <a name="r2section2"></a>
matrix, array는 벡터의 종류로 한 개의 데이터 타입만 지원합니다. 그에 반해 list 는 여러 데이터 종류를 결합할 수 있게 해 줍니다.  
또한 element들에 이름을 붙이는 것이 가능합니다.  

In [4]:
student1 <- list(name='chulsoo', score=70)
student2 <- list(name='younghee', score=80)
student3 <- list(name='doran', score=90)
student4 <- list(name='daeryuk', score=95)

In [5]:
student1$name
student1$score
student1[1] # list 항목 name
student1[2]
student1[[1]] # list 값
student1[[2]]

[1] "chulsoo"

[1] 70

$name
[1] "chulsoo"

$score
[1] 70

[1] "chulsoo"

[1] 70

<br>

## __Data Frame__ <a name="r2section3"></a>
일반적인 DB의 테이블과 유사한 형태입니다.  

In [6]:
name = c('chulsoo', 'younghee', 'doran', 'daeryuk')
score = c(70, 80, 90, 95)

In [7]:
tb1 <- data.frame(name, score)
print(tb1)
print(tb1$score)
print(tb1$score > 80)

      name score
1  chulsoo    70
2 younghee    80
3    doran    90
4  daeryuk    95
[1] 70 80 90 95
[1] FALSE FALSE  TRUE  TRUE


In [8]:
tb1$score[tb1$score>80] # True 값만 선택

[1] 90 95

In [9]:
math <- c(30, 40, 20, 15)
english <- c(50, 60, 70, 80)
tb2 <- data.frame(math, english)
print(tb2)

  math english
1   30      50
2   40      60
3   20      70
4   15      80


In [10]:
# 한 개의 row 는 컬럼명을 이용해 아래와 같이 정의할 수 있습니다.
stu1 <- data.frame('name'= 'changhee', score=30, math=40, english=50)
stu2 <- data.frame('name'= 'jaeyoung', score=30, math=40, english=50)

In [11]:
tb3 <- cbind(tb1, tb2) # column bind
print(tb3)
cat('\n')
tb4 <- rbind(tb3, stu1, stu2) # row bind
print(tb4)

      name score math english
1  chulsoo    70   30      50
2 younghee    80   40      60
3    doran    90   20      70
4  daeryuk    95   15      80

      name score math english
1  chulsoo    70   30      50
2 younghee    80   40      60
3    doran    90   20      70
4  daeryuk    95   15      80
5 changhee    30   40      50
6 jaeyoung    30   40      50


<br>

## __Model__ <a name="r2section4"></a>
변수 간 관계를 나타내는 Model 을 살펴봅니다.  
기본으로 주어진 cars 데이터를 이용합니다.

In [12]:
class(cars) # cars 는 data.frame 자료
cars[1:3,]

[1] "data.frame"

speed dist
1 4      2  
2 4     10  
3 7      4

In [13]:
model1 <- lm(formula=dist~speed, data=cars) # lm : linear model
model1
cat('\n\n============================\n\n')
summary(model1)


Call:
lm(formula = dist ~ speed, data = cars)

Coefficients:
(Intercept)        speed  
    -17.579        3.932  



Call:
lm(formula = dist ~ speed, data = cars)

Residuals:
    Min      1Q  Median      3Q     Max 
-29.069  -9.525  -2.272   9.215  43.201 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept) -17.5791     6.7584  -2.601   0.0123 *  
speed         3.9324     0.4155   9.464 1.49e-12 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 15.38 on 48 degrees of freedom
Multiple R-squared:  0.6511,	Adjusted R-squared:  0.6438 
F-statistic: 89.57 on 1 and 48 DF,  p-value: 1.49e-12


In [14]:
class(lm) # lm 은 선형 회귀 모델을 위한 함수
class(model1) # lm 모델의 결과는 lm 이라는 자료 구조(모델, 클래스)

[1] "function"

[1] "lm"

<br><br>

---
##### [이전 페이지](R_tutorial1.ipynb)
##### [다음 페이지](R_tutorial3.ipynb)