참고 https://keras.io/layers/core/

* 필요한 모델에 기본적으로 제공 되는 layer 이외의 기능이 필요한 경우  
* Layer 구성의 큰 변화없이 각 변수에 대한 단순 계산 적용은 Lambda layer 활용

In [1]:
from keras.models import Sequential, Model
from keras.layers import Dense, Activation, Lambda, Input
import numpy as np
from keras.optimizers import SGD

x_train = np.array([[1, 2, 3, 4]])
y_train = x_train * 2
print(x_train)
print(y_train)

Using TensorFlow backend.


[[1 2 3 4]]
[[2 4 6 8]]


* Sequence 가 아닌 Model을 이용해 모델을 생성해 보자
* 입력 값을 단순히 2배로 변환
* parameter 이 없는 것 확인 가능

In [2]:
inputs = Input(shape=(4,))
x2 = Lambda(lambda x: x * 2)(inputs)
model = Model(inputs=inputs, outputs=x2)
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 4)                 0         
_________________________________________________________________
lambda_1 (Lambda)            (None, 4)                 0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [3]:
model.predict(x_train)

array([[2., 4., 6., 8.]], dtype=float32)